language: php

php:
  - 7.2
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: cd tests/phpunit && ../../vendor/bin/phpunit --testdox